# Generated by Django 4.0.3 on 2022-03-24 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cat_user',
            new_name='create_by',
        ),
    ]
