# Generated by Django 4.0.3 on 2022-03-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_rename_cat_user_category_create_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='modify_date',
            field=models.DateTimeField(null=True),
        ),
    ]
